import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { NgxDatatableModule } from '@swimlane/ngx-datatable';
import { ResourceSearchDatatableComponent } from './resource-search-datatable.component';
import { SearchDatatableGenericResourceComponent } from './search-datatable-generic-resource/search-datatable-generic-resource.component';
import {
  DatatableFallbackComponent,
  DatatableAllergyIntoleranceComponent,
  DatatableAppointmentComponent,
  DatatableBinaryComponent,
  DatatableCarePlanComponent,
  DatatableCareTeamComponent,
  DatatableCommunicationComponent,
  DatatableConditionComponent,
  DatatableCoverageComponent,
  DatatableDeviceComponent,
  DatatableDeviceRequestComponent,
  DatatableDiagnosticReportComponent,
  DatatableDocumentReferenceComponent,
  DatatableEncounterComponent,
  DatatableGoalComponent,
  DatatableImmunizationComponent,
  DatatableLocationComponent,
  DatatableMedicationAdministrationComponent,
  DatatableMedicationComponent,
  DatatableMedicationDispenseComponent,
  DatatableMedicationRequestComponent,
  DatatableNutritionOrderComponent,
  DatatableObservationComponent,
  DatatableOrganizationComponent,
  DatatablePatientComponent,
  DatatablePractitionerComponent,
  DatatableProcedureComponent,
  DatatableServiceRequestComponent,
  DatatableRiskAssessmentComponent,
  DatatableRelatedPersonComponent,
  DatatablePractitionerRoleComponent,
  DatatableExplanationOfBenefitComponent,
  DatatableAdverseEventComponent,
} from './search-datatable-generic-resource/column-definitions';
import { ResourceSearchDatatableOutletDirective } from './resource-search-datable-outlet.directive';
import { FormsModule } from '@angular/forms';

@NgModule({
  declarations: [
    SearchDatatableGenericResourceComponent,
    ResourceSearchDatatableComponent,
    ResourceSearchDatatableOutletDirective,
    DatatableFallbackComponent,
    DatatableAllergyIntoleranceComponent,
    DatatableAppointmentComponent,
    DatatableBinaryComponent,
    DatatableCarePlanComponent,
    DatatableCareTeamComponent,
    DatatableCommunicationComponent,
    DatatableConditionComponent,
    DatatableCoverageComponent,
    DatatableDeviceComponent,
    DatatableDeviceRequestComponent,
    DatatableDiagnosticReportComponent,
    DatatableDocumentReferenceComponent,
    DatatableEncounterComponent,
    DatatableGoalComponent,
    DatatableImmunizationComponent,
    DatatableLocationComponent,
    DatatableMedicationAdministrationComponent,
    DatatableMedicationComponent,
    DatatableMedicationDispenseComponent,
    DatatableMedicationRequestComponent,
    DatatableNutritionOrderComponent,
    DatatableObservationComponent,
    DatatableOrganizationComponent,
    DatatablePatientComponent,
    DatatablePractitionerComponent,
    DatatableProcedureComponent,
    DatatableServiceRequestComponent,
    DatatableRiskAssessmentComponent,
    DatatableRelatedPersonComponent,
    DatatablePractitionerRoleComponent,
    DatatableExplanationOfBenefitComponent,
    DatatableAdverseEventComponent,
  ],
  imports: [NgxDatatableModule, CommonModule, FormsModule],
  exports: [
    SearchDatatableGenericResourceComponent,
    ResourceSearchDatatableComponent,
    ResourceSearchDatatableOutletDirective,
    DatatableFallbackComponent,
    DatatableAllergyIntoleranceComponent,
    DatatableAppointmentComponent,
    DatatableBinaryComponent,
    DatatableCarePlanComponent,
    DatatableCareTeamComponent,
    DatatableCommunicationComponent,
    DatatableConditionComponent,
    DatatableCoverageComponent,
    DatatableDeviceComponent,
    DatatableDeviceRequestComponent,
    DatatableDiagnosticReportComponent,
    DatatableDocumentReferenceComponent,
    DatatableEncounterComponent,
    DatatableGoalComponent,
    DatatableImmunizationComponent,
    DatatableLocationComponent,
    DatatableMedicationAdministrationComponent,
    DatatableMedicationComponent,
    DatatableMedicationDispenseComponent,
    DatatableMedicationRequestComponent,
    DatatableNutritionOrderComponent,
    DatatableObservationComponent,
    DatatableOrganizationComponent,
    DatatablePatientComponent,
    DatatablePractitionerComponent,
    DatatableProcedureComponent,
    DatatableServiceRequestComponent,
    DatatableRiskAssessmentComponent,
    DatatableRelatedPersonComponent,
    DatatablePractitionerRoleComponent,
    DatatableExplanationOfBenefitComponent,
    DatatableAdverseEventComponent
  ],
})
export class ResourceSearchDatatableModule {}
