#!/usr/bin/with-contenv bash

if [ -f "/opt/couchdb/data/.init_complete" ]; then
    echo "Couchdb initialization has already completed, skipping"
else

    # start couchdb as a background process (store PID)
    echo "Couchdb initialization: start couchdb in background mode"
    /opt/couchdb/bin/couchdb &
    COUCHDB_PID=$!

    # wait for couchdb to be ready
    until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:5984/_up); do echo "couchdb not ready" && sleep 5; done

    # create couch_peruser required system databases manually on startup
    echo "couchdb ready, start creating system databases"
    curl -X PUT http://127.0.0.1:5984/_users
    curl -X PUT http://127.0.0.1:5984/_replicator
    curl -X PUT http://127.0.0.1:5984/_global_changes
    echo "system databases created successfully"


    # gracefully stop couchdb process
    echo "killing couchdb process"
    kill -2 $COUCHDB_PID

    # create the init complete flag
    echo "Couchdb initialization: complete"
    touch /opt/couchdb/data/.init_complete
fi
