name: Fasten-Sources End-to-End Tests
# Todo: this should run on a schedule as well (weekly?)
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
env:
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: cd frontend && yarn install
      - name: Run Browserstack tests
        run: cd frontend && yarn run e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
